/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package pl.bartpos24.web.model

import android.os.Parcelable
import com.squareup.moshi.Json
import kotlinx.parcelize.Parcelize

/**
 *
 *
 * @param id
 * @param code
 * @param productId
 * @param product
 */
@Parcelize
data class Barcode(

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "productId")
    val productId: kotlin.Int? = null,

    @Json(name = "product")
    val product: Product? = null,

) : Parcelable
