/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model

import pl.bartpos24.web.model.Inventory
import pl.bartpos24.web.model.ProductUnit
import pl.bartpos24.web.model.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param productName 
 * @param quantity 
 * @param price 
 * @param scanDate 
 * @param userId 
 * @param inventoryId 
 * @param modifiedByUserId 
 * @param unitId 
 * @param isDeleted 
 * @param modificationDate 
 * @param unit 
 * @param user 
 * @param modifiedByUser 
 * @param inventory 
 */
@Parcelize


data class CommonInventoryPosition (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "productName")
    val productName: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Double? = null,

    @Json(name = "price")
    val price: kotlin.Double? = null,

    @Json(name = "scanDate")
    val scanDate: org.threeten.bp.LocalDateTime? = null,

    @Json(name = "userId")
    val userId: kotlin.Int? = null,

    @Json(name = "inventoryId")
    val inventoryId: kotlin.Int? = null,

    @Json(name = "modifiedByUserId")
    val modifiedByUserId: kotlin.Int? = null,

    @Json(name = "unitId")
    val unitId: kotlin.Int? = null,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Int? = null,

    @Json(name = "modificationDate")
    val modificationDate: org.threeten.bp.LocalDateTime? = null,

    @Json(name = "unit")
    val unit: ProductUnit? = null,

    @Json(name = "user")
    val user: User? = null,

    @Json(name = "modifiedByUser")
    val modifiedByUser: User? = null,

    @Json(name = "inventory")
    val inventory: Inventory? = null

) : Parcelable

