/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model

import pl.bartpos24.web.model.InventoryStatus
import pl.bartpos24.web.model.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 
 * @param executeWay 
 * @param responsiblePerson 
 * @param companyName 
 * @param companyAddress 
 * @param comissionTeam 
 * @param personToValue 
 * @param personToCheck 
 * @param createdAt 
 * @param startDate 
 * @param endDate 
 * @param createdByUserId 
 * @param inventoryStatusId 
 * @param createdByUser 
 * @param inventoryStatus 
 */
@Parcelize


data class Inventory (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "executeWay")
    val executeWay: kotlin.String? = null,

    @Json(name = "responsiblePerson")
    val responsiblePerson: kotlin.String? = null,

    @Json(name = "companyName")
    val companyName: kotlin.String? = null,

    @Json(name = "companyAddress")
    val companyAddress: kotlin.String? = null,

    @Json(name = "comissionTeam")
    val comissionTeam: kotlin.String? = null,

    @Json(name = "personToValue")
    val personToValue: kotlin.String? = null,

    @Json(name = "personToCheck")
    val personToCheck: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: org.threeten.bp.OffsetDateTime? = null,

    @Json(name = "startDate")
    val startDate: org.threeten.bp.OffsetDateTime? = null,

    @Json(name = "endDate")
    val endDate: org.threeten.bp.OffsetDateTime? = null,

    @Json(name = "createdByUserId")
    val createdByUserId: kotlin.Int? = null,

    @Json(name = "inventoryStatusId")
    val inventoryStatusId: kotlin.Int? = null,

    @Json(name = "createdByUser")
    val createdByUser: User? = null,

    @Json(name = "inventoryStatus")
    val inventoryStatus: InventoryStatus? = null

) : Parcelable

