/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model

import pl.bartpos24.web.model.ELoginType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param username 
 * @param password 
 * @param ssaid 
 * @param loginType 
 */
@Parcelize


data class LoginModel (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "ssaid")
    val ssaid: kotlin.String? = null,

    @Json(name = "loginType")
    val loginType: ELoginType? = null

) : Parcelable

