/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model

import pl.bartpos24.web.model.Barcode
import pl.bartpos24.web.model.InventoryPosition
import pl.bartpos24.web.model.Unit

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param name 
 * @param brand 
 * @param capacity 
 * @param label 
 * @param isGeneral 
 * @param unitId 
 * @param unit 
 * @param barcodes 
 * @param inventoryPositions 
 */
@Parcelize


data class Product (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @Json(name = "capacity")
    val capacity: kotlin.String? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "isGeneral")
    val isGeneral: kotlin.Boolean? = null,

    @Json(name = "unitId")
    val unitId: kotlin.Int? = null,

    @Json(name = "unit")
    val unit: Unit? = null,

    @Json(name = "barcodes")
    val barcodes: kotlin.collections.List<Barcode>? = null,

    @Json(name = "inventoryPositions")
    val inventoryPositions: kotlin.collections.List<InventoryPosition>? = null

) : Parcelable

