/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param name 
 * @param surname 
 * @param username 
 * @param email 
 * @param password 
 * @param confirmPassword 
 */
@Parcelize


data class RegisterModel (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "surname")
    val surname: kotlin.String,

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "confirmPassword")
    val confirmPassword: kotlin.String

) : Parcelable

