/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model

import pl.bartpos24.web.model.User
import pl.bartpos24.web.model.UserRole

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param userId 
 * @param userRoleId 
 * @param user 
 * @param userRole 
 */
@Parcelize


data class RoleForUser (

    @Json(name = "userId")
    val userId: kotlin.Int? = null,

    @Json(name = "userRoleId")
    val userRoleId: kotlin.Int? = null,

    @Json(name = "user")
    val user: User? = null,

    @Json(name = "userRole")
    val userRole: UserRole? = null

) : Parcelable

