/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param productName 
 * @param quantity 
 * @param unit 
 * @param price 
 * @param dateOfScanOrModification 
 */
@Parcelize


data class SummaryInventoryPosition (

    @Json(name = "productName")
    val productName: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Double? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null,

    @Json(name = "price")
    val price: kotlin.Double? = null,

    @Json(name = "dateOfScanOrModification")
    val dateOfScanOrModification: org.threeten.bp.LocalDateTime? = null

) : Parcelable

