/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model

import pl.bartpos24.web.model.UserInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param accessTokenExpiry 
 * @param refreshTokenExpiry 
 * @param tokenType 
 * @param user 
 */
@Parcelize


data class TokenResponse (

    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "refreshToken")
    val refreshToken: kotlin.String? = null,

    @Json(name = "accessTokenExpiry")
    val accessTokenExpiry: org.threeten.bp.OffsetDateTime? = null,

    @Json(name = "refreshTokenExpiry")
    val refreshTokenExpiry: org.threeten.bp.OffsetDateTime? = null,

    @Json(name = "tokenType")
    val tokenType: kotlin.String? = null,

    @Json(name = "user")
    val user: UserInfo? = null

) : Parcelable

