/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.model

import pl.bartpos24.web.model.RoleForUser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param name 
 * @param surname 
 * @param username 
 * @param email 
 * @param passowrd 
 * @param createdAt 
 * @param updatedAt 
 * @param roleForUsers 
 */
@Parcelize


data class User (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "surname")
    val surname: kotlin.String? = null,

    @Json(name = "username")
    val username: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "passowrd")
    val passowrd: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: org.threeten.bp.OffsetDateTime? = null,

    @Json(name = "updatedAt")
    val updatedAt: org.threeten.bp.OffsetDateTime? = null,

    @Json(name = "roleForUsers")
    val roleForUsers: kotlin.collections.List<RoleForUser>? = null

) : Parcelable

