/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.bartpos24.web.api

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import pl.bartpos24.web.model.CommonInventoryPosition
import pl.bartpos24.web.model.Inventory
import pl.bartpos24.web.model.InventoryPosition
import pl.bartpos24.web.model.SummaryInventoryPosition

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class InventoryApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * 
     * 
     * @param commonInventoryPosition  (optional)
     * @return CommonInventoryPosition
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryAddCommonInventoryPositionPost(commonInventoryPosition: CommonInventoryPosition? = null) : CommonInventoryPosition = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryAddCommonInventoryPositionPostWithHttpInfo(commonInventoryPosition = commonInventoryPosition)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CommonInventoryPosition
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param commonInventoryPosition  (optional)
     * @return ApiResponse<CommonInventoryPosition?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryAddCommonInventoryPositionPostWithHttpInfo(commonInventoryPosition: CommonInventoryPosition?) : ApiResponse<CommonInventoryPosition?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryAddCommonInventoryPositionPostRequestConfig(commonInventoryPosition = commonInventoryPosition)

        return@withContext request<CommonInventoryPosition, CommonInventoryPosition>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryAddCommonInventoryPositionPost
     *
     * @param commonInventoryPosition  (optional)
     * @return RequestConfig
     */
    fun apiInventoryAddCommonInventoryPositionPostRequestConfig(commonInventoryPosition: CommonInventoryPosition?) : RequestConfig<CommonInventoryPosition> {
        val localVariableBody = commonInventoryPosition
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/Inventory/AddCommonInventoryPosition",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryPosition  (optional)
     * @return InventoryPosition
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryAddInventoryPositionPost(inventoryPosition: InventoryPosition? = null) : InventoryPosition = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryAddInventoryPositionPostWithHttpInfo(inventoryPosition = inventoryPosition)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InventoryPosition
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryPosition  (optional)
     * @return ApiResponse<InventoryPosition?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryAddInventoryPositionPostWithHttpInfo(inventoryPosition: InventoryPosition?) : ApiResponse<InventoryPosition?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryAddInventoryPositionPostRequestConfig(inventoryPosition = inventoryPosition)

        return@withContext request<InventoryPosition, InventoryPosition>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryAddInventoryPositionPost
     *
     * @param inventoryPosition  (optional)
     * @return RequestConfig
     */
    fun apiInventoryAddInventoryPositionPostRequestConfig(inventoryPosition: InventoryPosition?) : RequestConfig<InventoryPosition> {
        val localVariableBody = inventoryPosition
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/Inventory/AddInventoryPosition",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventory  (optional)
     * @return kotlin.Int
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryCreateInventoryPost(inventory: Inventory? = null) : kotlin.Int = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryCreateInventoryPostWithHttpInfo(inventory = inventory)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Int
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventory  (optional)
     * @return ApiResponse<kotlin.Int?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryCreateInventoryPostWithHttpInfo(inventory: Inventory?) : ApiResponse<kotlin.Int?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryCreateInventoryPostRequestConfig(inventory = inventory)

        return@withContext request<Inventory, kotlin.Int>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryCreateInventoryPost
     *
     * @param inventory  (optional)
     * @return RequestConfig
     */
    fun apiInventoryCreateInventoryPostRequestConfig(inventory: Inventory?) : RequestConfig<Inventory> {
        val localVariableBody = inventory
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/Inventory/CreateInventory",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param commonInventoryPosition  (optional)
     * @return kotlin.Int
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryDeleteCommonInventoryPositionPost(commonInventoryPosition: CommonInventoryPosition? = null) : kotlin.Int = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryDeleteCommonInventoryPositionPostWithHttpInfo(commonInventoryPosition = commonInventoryPosition)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Int
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param commonInventoryPosition  (optional)
     * @return ApiResponse<kotlin.Int?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryDeleteCommonInventoryPositionPostWithHttpInfo(commonInventoryPosition: CommonInventoryPosition?) : ApiResponse<kotlin.Int?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryDeleteCommonInventoryPositionPostRequestConfig(commonInventoryPosition = commonInventoryPosition)

        return@withContext request<CommonInventoryPosition, kotlin.Int>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryDeleteCommonInventoryPositionPost
     *
     * @param commonInventoryPosition  (optional)
     * @return RequestConfig
     */
    fun apiInventoryDeleteCommonInventoryPositionPostRequestConfig(commonInventoryPosition: CommonInventoryPosition?) : RequestConfig<CommonInventoryPosition> {
        val localVariableBody = commonInventoryPosition
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/Inventory/DeleteCommonInventoryPosition",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryPosition  (optional)
     * @return kotlin.Int
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryDeleteInventoryPositionPost(inventoryPosition: InventoryPosition? = null) : kotlin.Int = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryDeleteInventoryPositionPostWithHttpInfo(inventoryPosition = inventoryPosition)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Int
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryPosition  (optional)
     * @return ApiResponse<kotlin.Int?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryDeleteInventoryPositionPostWithHttpInfo(inventoryPosition: InventoryPosition?) : ApiResponse<kotlin.Int?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryDeleteInventoryPositionPostRequestConfig(inventoryPosition = inventoryPosition)

        return@withContext request<InventoryPosition, kotlin.Int>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryDeleteInventoryPositionPost
     *
     * @param inventoryPosition  (optional)
     * @return RequestConfig
     */
    fun apiInventoryDeleteInventoryPositionPostRequestConfig(inventoryPosition: InventoryPosition?) : RequestConfig<InventoryPosition> {
        val localVariableBody = inventoryPosition
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/Inventory/DeleteInventoryPosition",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param commonInventoryPosition  (optional)
     * @return CommonInventoryPosition
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryEditCommonInventoryPositionPost(commonInventoryPosition: CommonInventoryPosition? = null) : CommonInventoryPosition = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryEditCommonInventoryPositionPostWithHttpInfo(commonInventoryPosition = commonInventoryPosition)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CommonInventoryPosition
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param commonInventoryPosition  (optional)
     * @return ApiResponse<CommonInventoryPosition?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryEditCommonInventoryPositionPostWithHttpInfo(commonInventoryPosition: CommonInventoryPosition?) : ApiResponse<CommonInventoryPosition?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryEditCommonInventoryPositionPostRequestConfig(commonInventoryPosition = commonInventoryPosition)

        return@withContext request<CommonInventoryPosition, CommonInventoryPosition>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryEditCommonInventoryPositionPost
     *
     * @param commonInventoryPosition  (optional)
     * @return RequestConfig
     */
    fun apiInventoryEditCommonInventoryPositionPostRequestConfig(commonInventoryPosition: CommonInventoryPosition?) : RequestConfig<CommonInventoryPosition> {
        val localVariableBody = commonInventoryPosition
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/Inventory/EditCommonInventoryPosition",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryPosition  (optional)
     * @return InventoryPosition
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryEditInventoryPositionPost(inventoryPosition: InventoryPosition? = null) : InventoryPosition = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryEditInventoryPositionPostWithHttpInfo(inventoryPosition = inventoryPosition)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InventoryPosition
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryPosition  (optional)
     * @return ApiResponse<InventoryPosition?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryEditInventoryPositionPostWithHttpInfo(inventoryPosition: InventoryPosition?) : ApiResponse<InventoryPosition?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryEditInventoryPositionPostRequestConfig(inventoryPosition = inventoryPosition)

        return@withContext request<InventoryPosition, InventoryPosition>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryEditInventoryPositionPost
     *
     * @param inventoryPosition  (optional)
     * @return RequestConfig
     */
    fun apiInventoryEditInventoryPositionPostRequestConfig(inventoryPosition: InventoryPosition?) : RequestConfig<InventoryPosition> {
        val localVariableBody = inventoryPosition
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/Inventory/EditInventoryPosition",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @param userId  (optional)
     * @return kotlin.collections.List<CommonInventoryPosition>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryGetAllCommonInventoryPositionsForUserGet(inventoryId: kotlin.Int? = null, userId: kotlin.Int? = null) : kotlin.collections.List<CommonInventoryPosition> = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryGetAllCommonInventoryPositionsForUserGetWithHttpInfo(inventoryId = inventoryId, userId = userId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CommonInventoryPosition>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @param userId  (optional)
     * @return ApiResponse<kotlin.collections.List<CommonInventoryPosition>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryGetAllCommonInventoryPositionsForUserGetWithHttpInfo(inventoryId: kotlin.Int?, userId: kotlin.Int?) : ApiResponse<kotlin.collections.List<CommonInventoryPosition>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryGetAllCommonInventoryPositionsForUserGetRequestConfig(inventoryId = inventoryId, userId = userId)

        return@withContext request<Unit, kotlin.collections.List<CommonInventoryPosition>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryGetAllCommonInventoryPositionsForUserGet
     *
     * @param inventoryId  (optional)
     * @param userId  (optional)
     * @return RequestConfig
     */
    fun apiInventoryGetAllCommonInventoryPositionsForUserGetRequestConfig(inventoryId: kotlin.Int?, userId: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (inventoryId != null) {
                    put("inventoryId", listOf(inventoryId.toString()))
                }
                if (userId != null) {
                    put("userId", listOf(userId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/Inventory/GetAllCommonInventoryPositionsForUser",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return kotlin.collections.List<CommonInventoryPosition>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryGetAllCommonInventoryPositionsGet(inventoryId: kotlin.Int? = null) : kotlin.collections.List<CommonInventoryPosition> = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryGetAllCommonInventoryPositionsGetWithHttpInfo(inventoryId = inventoryId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CommonInventoryPosition>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return ApiResponse<kotlin.collections.List<CommonInventoryPosition>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryGetAllCommonInventoryPositionsGetWithHttpInfo(inventoryId: kotlin.Int?) : ApiResponse<kotlin.collections.List<CommonInventoryPosition>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryGetAllCommonInventoryPositionsGetRequestConfig(inventoryId = inventoryId)

        return@withContext request<Unit, kotlin.collections.List<CommonInventoryPosition>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryGetAllCommonInventoryPositionsGet
     *
     * @param inventoryId  (optional)
     * @return RequestConfig
     */
    fun apiInventoryGetAllCommonInventoryPositionsGetRequestConfig(inventoryId: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (inventoryId != null) {
                    put("inventoryId", listOf(inventoryId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/Inventory/GetAllCommonInventoryPositions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @return kotlin.collections.List<Inventory>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryGetAllInventoriesGet() : kotlin.collections.List<Inventory> = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryGetAllInventoriesGetWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Inventory>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @return ApiResponse<kotlin.collections.List<Inventory>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryGetAllInventoriesGetWithHttpInfo() : ApiResponse<kotlin.collections.List<Inventory>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryGetAllInventoriesGetRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<Inventory>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryGetAllInventoriesGet
     *
     * @return RequestConfig
     */
    fun apiInventoryGetAllInventoriesGetRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/Inventory/GetAllInventories",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @param userId  (optional)
     * @return kotlin.collections.List<InventoryPosition>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryGetAllInventoryPositionsForUserGet(inventoryId: kotlin.Int? = null, userId: kotlin.Int? = null) : kotlin.collections.List<InventoryPosition> = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryGetAllInventoryPositionsForUserGetWithHttpInfo(inventoryId = inventoryId, userId = userId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<InventoryPosition>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @param userId  (optional)
     * @return ApiResponse<kotlin.collections.List<InventoryPosition>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryGetAllInventoryPositionsForUserGetWithHttpInfo(inventoryId: kotlin.Int?, userId: kotlin.Int?) : ApiResponse<kotlin.collections.List<InventoryPosition>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryGetAllInventoryPositionsForUserGetRequestConfig(inventoryId = inventoryId, userId = userId)

        return@withContext request<Unit, kotlin.collections.List<InventoryPosition>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryGetAllInventoryPositionsForUserGet
     *
     * @param inventoryId  (optional)
     * @param userId  (optional)
     * @return RequestConfig
     */
    fun apiInventoryGetAllInventoryPositionsForUserGetRequestConfig(inventoryId: kotlin.Int?, userId: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (inventoryId != null) {
                    put("inventoryId", listOf(inventoryId.toString()))
                }
                if (userId != null) {
                    put("userId", listOf(userId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/Inventory/GetAllInventoryPositionsForUser",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return kotlin.collections.List<InventoryPosition>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryGetAllInventoryPositionsGet(inventoryId: kotlin.Int? = null) : kotlin.collections.List<InventoryPosition> = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryGetAllInventoryPositionsGetWithHttpInfo(inventoryId = inventoryId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<InventoryPosition>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return ApiResponse<kotlin.collections.List<InventoryPosition>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryGetAllInventoryPositionsGetWithHttpInfo(inventoryId: kotlin.Int?) : ApiResponse<kotlin.collections.List<InventoryPosition>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryGetAllInventoryPositionsGetRequestConfig(inventoryId = inventoryId)

        return@withContext request<Unit, kotlin.collections.List<InventoryPosition>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryGetAllInventoryPositionsGet
     *
     * @param inventoryId  (optional)
     * @return RequestConfig
     */
    fun apiInventoryGetAllInventoryPositionsGetRequestConfig(inventoryId: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (inventoryId != null) {
                    put("inventoryId", listOf(inventoryId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/Inventory/GetAllInventoryPositions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return kotlin.collections.List<SummaryInventoryPosition>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryGetAllSummaryPositionsGet(inventoryId: kotlin.Int? = null) : kotlin.collections.List<SummaryInventoryPosition> = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryGetAllSummaryPositionsGetWithHttpInfo(inventoryId = inventoryId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SummaryInventoryPosition>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return ApiResponse<kotlin.collections.List<SummaryInventoryPosition>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryGetAllSummaryPositionsGetWithHttpInfo(inventoryId: kotlin.Int?) : ApiResponse<kotlin.collections.List<SummaryInventoryPosition>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryGetAllSummaryPositionsGetRequestConfig(inventoryId = inventoryId)

        return@withContext request<Unit, kotlin.collections.List<SummaryInventoryPosition>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryGetAllSummaryPositionsGet
     *
     * @param inventoryId  (optional)
     * @return RequestConfig
     */
    fun apiInventoryGetAllSummaryPositionsGetRequestConfig(inventoryId: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (inventoryId != null) {
                    put("inventoryId", listOf(inventoryId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/Inventory/GetAllSummaryPositions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return Inventory
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun apiInventoryGetInventoryByIdGet(inventoryId: kotlin.Int? = null) : Inventory = withContext(Dispatchers.IO) {
        val localVarResponse = apiInventoryGetInventoryByIdGetWithHttpInfo(inventoryId = inventoryId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Inventory
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param inventoryId  (optional)
     * @return ApiResponse<Inventory?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun apiInventoryGetInventoryByIdGetWithHttpInfo(inventoryId: kotlin.Int?) : ApiResponse<Inventory?> = withContext(Dispatchers.IO) {
        val localVariableConfig = apiInventoryGetInventoryByIdGetRequestConfig(inventoryId = inventoryId)

        return@withContext request<Unit, Inventory>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiInventoryGetInventoryByIdGet
     *
     * @param inventoryId  (optional)
     * @return RequestConfig
     */
    fun apiInventoryGetInventoryByIdGetRequestConfig(inventoryId: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (inventoryId != null) {
                    put("inventoryId", listOf(inventoryId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/Inventory/GetInventoryById",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
